### PR TITLE
Version 1.1.2

### LINKED ISSUE #7: Node 9 compatibility

### PR DESCRIPTION
**Pull request by jnordberg**
Closes #7 

### Changes

  * Use latest @steemit/rpc-auth (Node 9 compatibility)
  * Add Circle CI testrunners

### CODE REVIEW

**Comment by sneak** [comment]
that circleci docker caching version 2 shiz is amazing

**Review by sneak — APPROVED** [review]
lgtm. every time yarn.lock changes i get afraid

**Comment by jnordberg** [comment]
Yeah me also... This gave me an idea, a cli tool that takes a yarn.lock diff and gives a code diff

**Comment by jnordberg** [comment]
After writing that tool it could be added to circle ci runner and the results published as test artefacts just as the coverage reports (https://2-103996447-gh.circle-artifacts.com/0/reports/coverage/lcov-report/index.html)

**Pull request merged**
